/**
 * This file is auto-generated by the list-modules.ts script!
 * Do not modify this file manually!
 *
 * This file contains all exported components from the src directory and its subdirectories
 * and is used for tooling purposes.
 */
export default {
  'components/index.ts': ['ThHeader'],
  'components/ThButton/index.ts': ['ThButton', 'ThButtonLink'],
};
