/**
 * This file is auto-generated by the list-modules.ts script!
 * Do not modify this file manually!
 *
 * This file contains all exported components from the src directory and its subdirectories
 * and is used for tooling purposes.
 */
export default {
  'src/composables/index.ts': ['useScrollToTop'],
  'src/composables/useDarkmode/index.ts': ['useDarkmode'],
};
